name: Java Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compile
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn test

      - name: Package
        run: mvn package -DskipTests

      - name: Build Docker Image
        run: docker build -t calculator-app:${{ github.sha }} .
